name: Generate Trophies

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-trophies:
    runs-on: ubuntu-slim
    steps:
      - name: Generate Trophies
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: NullPointerDepressiveDisorder
          output_path: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
